TOPLEVEL_LANG=vhdl
VHDL_SOURCES = $(PWD)/../../src/axis_capturer.vhd
TOPLEVEL=axis_capturer
MODULE=axis_capturer_test
SIM=ghdl
SIM_ARGS=--wave=wave.ghw

include $(shell cocotb-config --makefiles)/Makefile.sim
